# Generated by Django 5.2.7 on 2025-11-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0004_remove_product_new_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='IsInStock',
        ),
    ]
